### PR TITLE
fix MigrateDir func

### LINKED ISSUE #197: Fix MigrateDir func
- [x]  nested directories under ($HOME/.config/$PROJECT_NAME) are not moved to a new location
- [x]  remove moved / empty directory.

ref: https://github.com/projectdiscovery/goflags/pull/114#pullrequestreview-1500839391

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #197.

### CODE REVIEW

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
Suggesting some possible improvements:
- We should error if the source and destination are the same folder. Otherwise, the files will overwrite themselves, and after the source folder is deleted
- `os.Stat` can be replaced with `fileutil.FileExist(...)` and `.FolderExist(...)`
- We should consider adding a couple of options to define if removing the source folder and considering a copy error on one file as fatal. What do you think?

**Comment by dogancanbakir** [comment]
> considering a copy error on one file as fatal.
@Mzack9999 What do you think about the best approach to take in this situation? Adding an option, for example, failOverCopyErr, and failing the process is what you think?

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
@dogancanbakir I think we can do the following:
- [ ] By default we remove the source folder (since it's a migration) and to disable this we define a global exported boolean variable
```go
var DeleteFolderAfterMigration = true
```
- [ ] We can define the error behavior with the idiomatic MustXXX pattern:
```go
func MustMigrateDir(sourceDir string, destinationDir string, removeSourceDir) error {
   return MigrateDir(sourceDir, destinationDir, false)
}
func MigrateDir(sourceDir string, destinationDir string, skipError bool) error {...}
```

**Comment by dogancanbakir** [comment]
@Mzack9999, I have made some alterations, although they may not be precisely what you had in mind. Nonetheless, the concept remains unchanged. Please share your thoughts on the updated version.

**Review by Mzack9999 — APPROVED** [review]

**Pull request merged**
