### PR TITLE
add version bump script

### LINKED ISSUE #217: Add version bump script
Ref: https://github.com/projectdiscovery/cdncheck/pull/121#pullrequestreview-1543410635

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #217.

### CODE REVIEW

**Review by tarunKoyalwar — COMMENTED** [review]
suggesting adding unit tests with below testcases
```
v1.0.0
1.0.8
v1.0.9-dev
1.0.85.1  // invalid
```
also just in case i think we should add prefix `v` if it is missing (earlier there were some inconsistencies regarding this)

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
As mentioned by @tarunKoyalwar let's add some test cases, in addition to the ones mentioned:
- Unwanted prefixes/suffixes: new lines, spaces, multiple dots
- Negative numbers
- Unparseable numbers

**Review by Mzack9999 — APPROVED** [review]
lgtm!

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

**Review by Mzack9999 — APPROVED** [review]

**Pull request merged**
