### PR TITLE
adds channel utils for mux and demux

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed Changes

- add util to join N channels
- add util to Clone N channels
- closes https://github.com/projectdiscovery/utils/issues/193

### CODE REVIEW

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
The implementation looks good, and I like the idea of buffering to avoid blocking. Conversely, the classical for loop with go routines offers a simpler self-cleaning mechanism. I also considered adding disk-based buffer storage for slow consumers (a simple go cheap alternative for rabbitmq for internal use only).

- [ ] Could you replace the `gologger.xxx` with a return error statement so the caller can handle it?

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
Not sure if it's a common issue, but I had to fork multiple repositories as they were printing to stdout unwanted data, so I'd propose two options:
- error buffered channel as you proposed
- Add a `log.Logger` to the struct
```go
type JoinChannels[T any] struct {
	...
	Log *log.Logger
	...
}
...
// something like this to print to the logger
func (j *JoinChannels[T]) log(f string, args ...any) {
	if j.Log != nil {
		j.Log.Printf(f, args...)
	}
}
```

What do you think?

**Comment by tarunKoyalwar** [comment]
@Mzack9999 , yeah do you think we should implement both of them or one of proposed .  if we have a choice i think we should probably use error channel approach since utils is library the error can be properly propogated to downstream repos

**Review by Mzack9999 — APPROVED** [review]
lgtm!

**Pull request merged**
