### PR TITLE
add more unit test for url fragment parsing

### LINKED ISSUE #247: urlutil.ParseURL(...) with empty fragment
The function `urlutil.ParseURL(...)` seems to not parse correctly the Fragment part of the url

```console
$ cat main.go
package main

import (
	"log"

	urlutil "github.com/projectdiscovery/utils/url"
)

func main() {
	u, err := urlutil.ParseURL("https://admin/aaa#vvvv", false)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(u.Fragment)
}
$ go run .
2023/08/23 22:48:05 
```

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #247.

Before:
```console
$ cat main.go
package main

import (
	"log"

	urlutil "github.com/projectdiscovery/utils/url"
)

func main() {
	u, err := urlutil.ParseURL("https://admin/aaa#vvvv", false)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(u.Fragment)
}
$ go run .
2023/08/23 22:48:05 
```

After:
```console
$ cat main.go 
package main

import (
        "log"

        urlutil "github.com/projectdiscovery/utils/url"
)

func main() {
        u, err := urlutil.ParseURL("https://admin?param=value#high", false)
        if err != nil {
                log.Fatal(err)
        }
        log.Println(u.Fragment)
        log.Println(u.RawQuery)
}

$ go run .
2023/08/24 10:53:12 high
2023/08/24 10:53:12 param=value
```

### CODE REVIEW

**Review by tarunKoyalwar — APPROVED** [review]
@Mzack9999 @dogancanbakir 

not sure why @Mzack9999 was facing fragment parsing issue but the functionality seems to be already working 

see: 
https://github.com/projectdiscovery/utils/blob/92bd1da0f15b1712022db773b86fd2a348ec5a54/url/url_test.go#L49-L55

^ we had this unit test for fragment ~7 months . and it would have been detected if there was a parsing error

i updated unit test to cover more edgecases (i.e relative url , absolute url etc) . and also changed PR title

@Mzack9999 can you confirm if you are still facing this issue ? i was not able to reproduce this so was @RamanaReddy0M

**Comment by dogancanbakir** [comment]
@tarunKoyalwar, Regarding the issue raised by @Mzack9999. The URL has only the SDL and lacks the TLD. Adding the TLD might be the fix we're looking for. However, I don't know if that's the expected behavior  /shrug.

**Comment by tarunKoyalwar** [comment]
@dogancanbakir , url.Parse() does a loose parsing i.e it allows other protocols , relative paths , absolute paths , url without scheme etc which created a lot of issues for us and more edgecases . to counter this we added a strict parsing approach in `ParseURL` <- for both absolute and relative url 
`ParseRelativePath` <- should only be used for relative path 

my guess is that this was caused due to that issue . also for context purpose check this out
https://github.com/projectdiscovery/utils/blob/92bd1da0f15b1712022db773b86fd2a348ec5a54/url/url.go#L291-L303

^ we only have a very abstract implementation of validating a domain . so if we add support for non-standard domains names like `admin` or something else by adding them to `/etc/hosts` file . we won't be able to seperate them from relative path unless we do a probe or something else (which will drastically complicate things)

**Comment by tarunKoyalwar** [comment]
i have not verified what causing issue with fragment when using non-standard urls but if it can be fixed without removing / breaking any functionality we should do that . 

i will try to debug later on  what might be causing issue

**Review by Mzack9999 — APPROVED** [review]

**Pull request merged**
